### ISSUE TITLE
Scoreboard is not working.

### ISSUE THREAD

**Issue by emcho99** [nkokor/flappy-bird#1]
Hello this is my favorite game please fix the scoreboard.

**Comment by nkokor** [comment]
> Hello this is my favorite game please fix the scoreboard.

thanks for the feedback, the issue is fixed and score tracking should be accurate now

**Comment by nkokor** [comment]
> Hello this is my favorite game please fix the scoreboard.

thanks for the feedback, the issue is fixed and score tracking should be accurate now
